services:
  db:
    image: mysql:8.0
    container_name: bookportal-mysql
    environment:
      MYSQL_DATABASE: bookportal
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql
      - ./dbData:/docker-entrypoint-initdb.d   # unzip dbData.zip here (contains .sql)
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -psecret --silent"]
      interval: 5s
      timeout: 5s
      retries: 30

  book-portal-be:
    image: ugurcanerdogan/book-portal-be:latest
    container_name: book-portal-be
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/bookportal?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: secret
      # Optional but safe:
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect

  book-portal-fe:
    image: ugurcanerdogan/book-portal-fe:latest
    container_name: book-portal-fe
    expose:
      - "3000"
    depends_on:
      - book-portal-be

  proxy:
    build: ./nginx
    container_name: book-portal-nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - book-portal-fe
      - book-portal-be

volumes:
  dbdata:
