# name: Deploy via SSH (no IAM)

on:
  workflow_run:
    workflows: ['Node.js CI', 'Java CI with Maven']   # deploy after either CI succeeds
    types: [completed]
  workflow_dispatch: {}                                # manual "Run workflow"

jobs:
  deploy:
    if: ${{ (github.event.workflow_run && github.event.workflow_run.conclusion == 'success') || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    env:
      HOST: ${{ secrets.EC2_HOST }}                   # Elastic IP or Public DNS
      USER: ${{ secrets.EC2_USER }}                   # set this secret to: ubuntu
      DH_USER: ${{ secrets.DOCKER_HUB_USERNAME }}     # rcui2
      DH_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    steps:
      - name: Write private key
        shell: bash
        run: |
          umask 077
          cat > key.pem <<'EOF'
${{ secrets.EC2_KEY }}
EOF
          chmod 600 key.pem

      - name: SSH smoke test
        shell: bash
        run: |
          ssh -o StrictHostKeyChecking=no -o ConnectTimeout=20 -i key.pem "$USER@$HOST" \
            'whoami && hostname && ls -la /home/ubuntu'

      - name: Remote docker compose refresh
        shell: bash
        run: |
          ssh -o StrictHostKeyChecking=no -o ConnectTimeout=30 -i key.pem "$USER@$HOST" '
            set -e
            cd /home/ubuntu
            docker login -u "'"$DH_USER"'" -p "'"$DH_TOKEN"'"
            docker compose pull
            docker compose up -d
            docker image prune -af || true
          '
